export const legacyRedirects: Record<string, string> = {
  "/tips-memilih-paving-beton-yang-tahan-lama": "/id/blog/panduan-memilih-paving-block-hunian-proyek",
  "/desain-paving-rumah-minimalis-yang-menawan": "/id/projects",
  "/inspirasi-desain-menarik-dengan-paving-block-merah": "/id/projects",
  "/supplier-paving-block-terpercaya-kuat-rapi-dan-estetis": "/id/products",
  "/jual-paving-block-murah": "/id/products",
  "/panduan-pasang-paving-hexagon-agar-rapi-dan-tahan-lama": "/id/blog/persiapan-sebelum-pemasangan-paving-block",
  "/kelebihan-paving-hexagon-untuk-halaman-rumah-dan-taman": "/id/products",
  "/proses-pemasangan-paving-block-yang-benar-dan-rapi": "/id/blog/persiapan-sebelum-pemasangan-paving-block",
  "/inspirasi-desain-lantai-dengan-paving-bata": "/id/projects",
  "/paving-bata-vs-beton-mana-yang-lebih-baik": "/id/blog/perbandingan-paving-block-aspal-cor-beton",
  "/paving-block-sebagai-alternatif-material-ramah-lingkungan": "/id/blog/paving-block-ramah-lingkungan-resapan-air",
  "/paving-block-interlocking-keunggulan-dan-cara-pemasangannya": "/id/blog/persiapan-sebelum-pemasangan-paving-block",
  "/cara-menghitung-kebutuhan-paving-block-per-meter-persegi": "/id/blog/cara-merencanakan-kebutuhan-paving-block",
  "/paving-block-aman-dan-estetik-untuk-sekolah-dan-fasilitas-umum": "/id/blog/panduan-memilih-paving-block-hunian-proyek",
  "/paving-block-untuk-drainase-manfaat-dan-cara-kerjanya": "/id/blog/paving-block-ramah-lingkungan-resapan-air",
  "/cara-memilih-kontraktor-pemasangan-paving-block-terpercaya": "/id/contact",
  "/paving-block-custom-untuk-tampilan-halaman-lebih-estetik": "/id/projects",
  "/tren-desain-paving-block-tahun-ini-minimalis-dan-elegan": "/id/projects",
  "/mengapa-paving-block-ramah-lingkungan-ini-penjelasannya": "/id/blog/paving-block-ramah-lingkungan-resapan-air",
  "/mengatasi-paving-block-yang-tenggelam-atau-bergelombang": "/id/blog/tips-merawat-paving-block",
  "/jual-paving-block-berkualitas-solusi-kuat-dan-estetis-untuk-lantai-eksterior": "/id/products",
  "/jual-conblock-custom-desain-unik-untuk-tampilan-lebih-menarik": "/id/projects",
  "/jual-paving-block-segi-enam-pilihan-tepat-untuk-jalan-dan-taman": "/id/products",
  "/teknik-pemasangan-paving-block-yang-benar-agar-tahan-lama": "/id/blog/persiapan-sebelum-pemasangan-paving-block",
  "/jual-conblock-murah-untuk-halaman-jalan-dan-area-komersial": "/id/products",
  "/jual-paving-block-interlock-pilihan-ideal-untuk-jalan-raya-dan-trotoar": "/id/products",
  "/inspirasi-desain-paving-block-untuk-halaman-rumah-yang-estetik": "/id/projects",
  "/perbandingan-paving-block-dan-cor-beton-mana-yang-lebih-baik": "/id/blog/perbandingan-paving-block-aspal-cor-beton",
  "/jual-conblock-berbagai-model-dan-ukuran-cocok-untuk-semua-kebutuhan": "/id/products",
  "/kelebihan-paving-block-untuk-jalan-perumahan-dan-area-parkir": "/id/blog/paving-block-parkir-pergudangan-kawasan-industri",

  "/id/blog/mutu-beton-k300-k350-paving-block": "/id/blog/mutu-beton-k250-k300-k400-paving-block",
  "/en/blog/mutu-beton-k300-k350-paving-block": "/en/blog/mutu-beton-k250-k300-k400-paving-block",
};

